name: Déploiement de l'Application React sur GitHub Pages

on:
  push:
    branches: [main] # On ne déploie que ce qui est sur la branche principale

jobs:
  build-and-test: # Le nom de notre premier job
    name: Construire et Tester
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout du code
        uses: actions/checkout@v4

      # Étape 2 : Mettre en place l'environnement Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # On spécifie une version LTS (Long Term Support)
          cache: "npm" # Active le caching pour npm automatiquement
          cache-dependency-path: cypress-react-app/package-lock.json

      # Étape 3 : Installer les dépendances
      - name: Installation des dépendances
        run: npm ci
        working-directory: cypress-react-app

      # Étape 4 : Lancer les tests
      - name: Exécution des tests
        run: npm test
        working-directory: cypress-react-app

      # Étape 5 : Construire l'application
      - name: Build de l'application
        run: npm run build
        working-directory: cypress-react-app

      # Nouvelle Étape : Uploader l'artefact du build
      - name: Uploader l'artefact de build
        uses: actions/upload-pages-artifact@v3
        with:
          # Le dossier à uploader, qui a été généré par 'npm run build'
          path: "./build"

  # --- NOTRE NOUVEAU JOB DE DÉPLOIEMENT ---
  deploy:
    name: Déployer sur GitHub Pages
    # Ce job ne commencera que si le job 'build-and-test' a réussi
    needs: build-and-test

    # Permissions nécessaires pour que le job puisse écrire sur GitHub Pages
    permissions:
      pages: write # pour écrire sur l'environnement GitHub Pages
      id-token: write # pour s'authentifier auprès de GitHub Pages

    # L'environnement de déploiement (optionnel mais bonne pratique)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      # L'étape finale : prendre l'artefact uploadé et le déployer
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4