name: CI pour le projet Django

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lancer les tests unitaires
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # On peut tester sur plusieurs versions ici

    steps:
      - name: 1. Checkout du code
        uses: actions/checkout@v4

      - name: 2. Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 3. Cache des dépendances pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4. Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r my_api_project/requirements.txt

      - name: 5. Exécution des tests
        run: |
          python manage.py test
        working-directory: my_api_project